GPIO_BUTTON(1, GPIO_BTN1_PIN, GPIO_BTN1_PORT, GPIO_BTN1_BUS)
GPIO_BUTTON(2, GPIO_BTN2_PIN, GPIO_BTN2_PORT, GPIO_BTN2_BUS)
GPIO_BUTTON(3, GPIO_BTN3_PIN, GPIO_BTN3_PORT, GPIO_BTN3_BUS)
GPIO_BUTTON(4, GPIO_BTN4_PIN, GPIO_BTN4_PORT, GPIO_BTN4_BUS)