#pragma once

#define EMULATE_VPRINTF 1

#define TS_LOG_DEFALUT 0

#define DEFAULT_GAME GameById(attract)

#define CONFIG_SLEEP_MODE 1

#define BLOCK_SLEEP_MODE_TIMEOUT 10000

#define CONFIG_BEEPER_VOLUME_BASE 1000
#define CONFIG_BEEPER_VOLUME 300