GPIO_LED(1, GPIO_LED1_PIN, GPIO_LED1_PORT, low, GPIO_LED1_BUS)
GPIO_LED(2, GPIO_LED2_PIN, GPIO_LED2_PORT, low, GPIO_LED2_BUS)
GPIO_LED(3, GPIO_LED3_PIN, GPIO_LED3_PORT, low, GPIO_LED3_BUS)
GPIO_LED(4, GPIO_LED4_PIN, GPIO_LED4_PORT, low, GPIO_LED4_BUS)